# 08-12. 연결된 예외(chained exception)
한 예외가 다른 예외를 발생시킬 수도 있다. 
예를 들어 예외 A가 예외 B를 발생시켰다면, A를 B의 '원인 예외(cause exception)'라고 한다.
```java
try {
  startinstall(); //SpaceException 발생
  copyFiles();
} catch(SpaceException e) {
  InstallException ie = new InstallException("설치중 예외발생"); //예외 생성
  ie.initCause(e); //InstallException의 원인 예외를 SpaceException으로 지정
  throw ie; //InstallException을 발생시킨다.
} catch(MemoryException me) {
```
initCause()는 Exception클래스의 조상인 Throwable클래스에 정의되어 있기 때문에 모든 예외에서 사용가능하다.
```java
  Throwable initCause(Throwable cause) //지정한 예외를 원인 예외로 등록
  Throwable getCause() //원인 예외를 반환
```
발생한 예외를 그냥 처리하면 될 텐데, 원인 예외로 등록해서 다시 예외를 발생시키는지 궁금할 것이다. 
그 이유는 여러가지 예외를 하나의 큰 분류의 예외로 묶어서 다루기 위해서이다.

그렇다고 InstallException을 SpaceException과 MemoryException의 조상으로 해서 catch블럭을 작성하면, 
실제로 발생한 예외가 어떤 것인지 알 수 없다는 문제가 생긴다. 
그리고 SpaceException과 MemoryException의 상속관계를 변경해야 한다는 것도 부담이다.
```java
try {
  startinstall(); //SpaceException 발생
  copyFiles();
} catch(InstallException e) { //InstallException은
  e.printStackTrace(); //SpaceException과 MemoryException의 조상
}
```

그래서 생각한 것이 예외가 원인 예외를 포함할 수 있게 한 것이다. 
이렇게 하면, 두 예외는 상속관계가 아니어도 상관없다.

또 다른 이유는 checked예외를 unchecked예외로 바꿀 수 있도록 하기 위해서이다.
checked예외가 발생해도 예외를 처리할 수 없는 상황에 할 수 있는 일이라곤 의미없는 try-catch문을 추가하는 것뿐인데,
unchecked예외로 바꾸면 예외처리가 선택적이 되므로 억지로 예외처리를 하지 않아도 된다.
```java
static void startinstall() throws SpaceException {
  if(!enoughspace()) //충분한 설치 공간이 없으면
    throw new SpaceException("설치할 공간이 부족합니다.");
  if(!enoughMemory()) //충분한 메모리가 없으면
    throw new RuntimeException(new MemoryException("메모리가 부족합니다."));
  } //startinstall메서드의 끝
```
위 코드는 initCause()대신 RuntimeException의 생성자를 사용했다.
```java
RuntimeException(Throwable cause) //원인 예외를 등록하는 생성자
```
```java
```
```
```
