# 08-9. 자동 자원 반환 - try-with-resources
JDK1.7부터 try-with-resources문이라는 try-catch문의 변형이 새로 추가되었다.

주로 입출력에 사용되는 클래스 중에서는 사용한 후에 꼭 닫아 줘야 하는 것들이 있다.
그래야 사용했던 자원(resources)이 반환되기 때문이다.
```java
try {
  fis = new Fileinputstream("score.dat");
  dis = new DataInputStream(fis);
} catch(IOException ie) {
  ie.printStackTrace();
} finally {
  try {
    if(dis! = null)
    dis.close();
  } catch(IOException ie) {
    ie.printStackTrace();
  }
}
```
위의 코드는 DataInputStream을 사용해서 파일로부터 데이터를 읽는 코드인데,
데이터를 읽는 도중에 예외가 발생하더라도 DataInputStream이 닫히도록 finally블럭 안에 close()를 넣었다.
그런데, close() 역시 예외를 발생시킬 수 있기 때문에 finally블럭 안에 try-catch문을 추가해서 예외를 처리하도록 했다.
코드가 복잡해져서 별로 보기에 좋지 않다. 더 나쁜 것은 try블럭과 finally블럭에서 모두 예외가 발생하면, try블럭의 예외는 무시된다는 것이다.
